package End2EndSimplified.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Canvas = 1;
  public static final int Click = 2;
  public static final int ClickRefernce = 3;
  public static final int Wait = 4;
  public static final int clickButtons = 5;
  public static final int screenshot = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L);
    builder.put(0x122ee31aafdee25dL, Action);
    builder.put(0x122ee31aafdee2a0L, Canvas);
    builder.put(0x122ee31aafdee25eL, Click);
    builder.put(0x66075fb65b455a11L, ClickRefernce);
    builder.put(0x66075fb65b46dcdcL, Wait);
    builder.put(0x66075fb65b46366cL, clickButtons);
    builder.put(0x122ee31aafe25c9cL, screenshot);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
