package End2EndSimplified.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptClick = createDescriptorForClick();
  /*package*/ final ConceptDescriptor myConceptClickRefernce = createDescriptorForClickRefernce();
  /*package*/ final ConceptDescriptor myConceptWait = createDescriptorForWait();
  /*package*/ final ConceptDescriptor myConceptclickButtons = createDescriptorForclickButtons();
  /*package*/ final ConceptDescriptor myConceptscreenshot = createDescriptorForscreenshot();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptCanvas, myConceptClick, myConceptClickRefernce, myConceptWait, myConceptclickButtons, myConceptscreenshot);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Click:
        return myConceptClick;
      case LanguageConceptSwitch.ClickRefernce:
        return myConceptClickRefernce;
      case LanguageConceptSwitch.Wait:
        return myConceptWait;
      case LanguageConceptSwitch.clickButtons:
        return myConceptclickButtons;
      case LanguageConceptSwitch.screenshot:
        return myConceptscreenshot;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "Action", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25dL);
    b.class_(false, true, false);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/1310234245370667613");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "Canvas", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee2a0L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/1310234245370667680");
    b.version(2);
    b.property("URL", 0x66075fb65b468766L).type(PrimitiveTypeId.STRING).origin("7351950153525659494").done();
    b.aggregate("actions", 0x122ee31aafdee2a1L).target(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25dL).optional(true).ordered(true).multiple(true).origin("1310234245370667681").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "Click", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25eL);
    b.class_(false, false, true);
    b.super_("End2EndSimplified.structure.Action", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25dL);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/1310234245370667614");
    b.version(2);
    b.property("param", 0x62655555afee3f8L).type(PrimitiveTypeId.STRING).origin("443135438429807608").done();
    b.aggregate("ClickWhat", 0x66075fb65b455a3cL).target(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b455a11L).optional(false).ordered(true).multiple(false).origin("7351950153525582396").done();
    b.alias("click");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickRefernce() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "ClickRefernce", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b455a11L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/7351950153525582353");
    b.version(2);
    b.associate("target", 0x66075fb65b463695L).target(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b46366cL).optional(false).origin("7351950153525638805").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWait() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "Wait", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b46dcdcL);
    b.class_(false, false, false);
    b.super_("End2EndSimplified.structure.Action", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25dL);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/7351950153525681372");
    b.version(2);
    b.property("Time", 0x66075fb65b46dcddL).type(PrimitiveTypeId.INTEGER).origin("7351950153525681373").done();
    b.alias("wait");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForclickButtons() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "clickButtons", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b46366cL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/7351950153525638764");
    b.version(2);
    b.alias("click buttons");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForscreenshot() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("End2EndSimplified", "screenshot", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafe25c9cL);
    b.class_(false, false, false);
    b.super_("End2EndSimplified.structure.Action", 0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25dL);
    b.origin("r:7ad78c9e-5ea8-4c5e-949d-e12666dc0a6a(End2EndSimplified.structure)/1310234245370895516");
    b.version(2);
    b.property("fileName", 0x122ee31aafe25c9dL).type(PrimitiveTypeId.STRING).origin("1310234245370895517").done();
    b.alias("screenshot");
    return b.create();
  }
}
