package End2EndSimplified.sandbox;

/*Generated by MPS */

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.By;

public class map_Canvas {
  public static void main(String[] args) throws InterruptedException {
    System.setProperty("webdriver.chrome.driver", "/home/zachary/Desktop/chromedriver");
    WebDriver driver = new ChromeDriver();
    driver.get("https://www.test.com");
    try {
      System.out.println(5000);
      Integer i = 5000;
      Long l = Long.valueOf(i);
      Thread.sleep(l);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    try {
      System.out.println(6000);
      Integer i = 6000;
      Long l = Long.valueOf(i);
      Thread.sleep(l);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.className("gauge-button")).click();
    try {
      System.out.println(2000);
      Integer i = 2000;
      Long l = Long.valueOf(i);
      Thread.sleep(l);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.linkText("Tour")).click();
    try {
      System.out.println(3000);
      Integer i = 3000;
      Long l = Long.valueOf(i);
      Thread.sleep(l);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.linkText("Pricing")).click();
    try {
      System.out.println(4000);
      Integer i = 4000;
      Long l = Long.valueOf(i);
      Thread.sleep(l);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.quit();
  }
}
