package End2EndSimplified.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Canvas_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Click_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ClickRefernce_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Wait_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new clickButtons_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new screenshot_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        if (true) {
          if ("End2EndSimplified.editor.ClickAction".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new ClickAction());
          }
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }

  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ClickRefernce_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee2a0L), MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25eL), MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b455a11L), MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b46dcdcL), MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b46366cL), MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafe25c9cL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x122ee31aafdee25eL)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3797ae2e6d9d425bL, 0xa7f89fe085cb1810L, 0x66075fb65b455a11L)).seal();
}
